[package]
name = "cred-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.34", features = ["derive"] }
jsonwebtoken = "9.3.1"
octocrab = "0.44.0"
rand = "0.9.0"
tokio = { version = "1.44.2", features = ["full"] }
